import type { SlideModule } from '../../../src/types'
import { Callout, Slide, SlideHeading, TitleSlide } from '../../../src/slide-kit'
import { NetworkVisual } from '../../network-series/NetworkVisual'
import { PacketView } from '../../network-series/PacketView'

export const slides: SlideModule['slides'] = [
  { id: 'opening', render: ({ frame }) => <TitleSlide frame={frame} kicker="ネットワーク超基礎 · 第1話" heading={'Wi-Fiにつないだだけで、\nなぜWebページが開く？'} lead="自分のPCから出発して、何が起こるか追跡しよう" points={[{ step: '01', heading: '家の中', body: 'Wi-Fiとルーター' }, { step: '02', heading: '家の外', body: 'IPで経路をつなぐ' }, { step: '03', heading: '往復', body: '返事をPCに届ける' }]} /> },
  { id: 'two-connections', render: (props) => <NetworkVisual {...props} mode="layers" kicker="本の説明①：まず線を見る" heading="Wi-Fiは家の中の、最初の一区間" lead="電波が届いても、インターネットの道が開通したとは限らない" caption="PC → Wi-Fi／ルーター → 回線 → Webサイト" note="Wi-Fi接続と外の回線は別々。" /> },
  { id: 'route', render: (props) => <NetworkVisual {...props} mode="dns" kicker="本の説明②：URLの次に何をする？" heading="名前だけでは届けられない" lead="example.com のIPアドレスをDNSで調べる" caption="まずWebサイトの名前 → IPアドレスへ変換" note="203.0.113.10 は資料用の番号。" /> },
  { id: 'dns-packet', render: (props) => <PacketView {...props} kicker="DNSの問い合わせ・中身を開ける" heading="DNSのパケットを開ける" lead="PCが送る『質問』と、ルーターから返る『答え』" caption="DNSの質問と答え（UDP 53番）" note="答えの 203.0.113.10 が、次の通信の宛先IPになる。" columns={[{ label: '① 質問：PC → ルーター', body: '家のルーターがDNSの窓口役' }, { label: '② 答え：ルーター → PC', body: '送信元と宛先が入れ替わる' }]} rows={[{ kind: 'eth', heading: 'Ethernetヘッダー ─ この区間の宛名', items: [{ label: '宛先MAC', cells: ['00-00-5E-00-53-01（ルーター）', '00-00-5E-00-53-10（PC）'] }, { label: '送信元MAC', cells: ['00-00-5E-00-53-10（PC）', '00-00-5E-00-53-01（ルーター）'] }] }, { kind: 'ip', heading: 'IPヘッダー', items: [{ label: '送信元IP', cells: ['192.168.1.10', '192.168.1.1'] }, { label: '宛先IP', cells: ['192.168.1.1', '192.168.1.10'] }] }, { kind: 'udp', heading: 'UDPヘッダー', items: [{ label: '送信元ポート', cells: ['53124', '53（DNS）'] }, { label: '宛先ポート', cells: ['53（DNS）', '53124'] }] }, { kind: 'data', heading: 'DNSメッセージ', items: [{ label: '質問', cells: ['example.com のIPv4は？', 'example.com のIPv4は？'] }, { label: '答え', cells: ['（まだ空）', '203.0.113.10'], changed: true }] }]} /> },
  { id: 'return', render: (props) => <NetworkVisual {...props} mode="gateway" kicker="本の説明③：次は誰に渡す？" heading="外の宛先なら、まず家の出口へ" lead="PCは世界の道順を知らない。デフォルトゲートウェイに頼む" caption="目的地のIPと、最初に渡す相手は別" note="PCは世界中の道順を知らない。" /> },
  { id: 'packet-anatomy', render: (props) => <PacketView {...props} kicker="本の説明③の続き：実際に何が飛ぶ？" heading="パケットは封筒の入れ子" lead="外側から、区間の宛名 → 最終宛先 → アプリ → 中身" caption="PC → ルーターの区間を流れる1個のパケット" note="宛先MACはルーター、宛先IPはWebサイト。" columns={[{ label: 'Webページをください（HTTPS）：この全部が1かたまりで流れる' }]} rows={[{ kind: 'eth', heading: 'Ethernetヘッダー ─ この区間だけの宛名', items: [{ label: '宛先MAC', cells: ['00-00-5E-00-53-01（ルーター）'], changed: true }, { label: '送信元MAC', cells: ['00-00-5E-00-53-10（PC）'] }, { label: '中身の種類', cells: ['0x0800 = IPv4'] }] }, { kind: 'ip', heading: 'IPヘッダー ─ 最終目的地までの宛名', items: [{ label: '送信元IP', cells: ['192.168.1.10（PC）'] }, { label: '宛先IP', cells: ['203.0.113.10（Webサイト）'], changed: true }, { label: 'TTL', cells: ['64（ルーターを通るたびに1減る）'] }, { label: '中身の種類', cells: ['6 = TCP'] }] }, { kind: 'tcp', heading: 'TCPヘッダー ─ どのアプリ宛てか', items: [{ label: '送信元ポート', cells: ['50123（ブラウザ側の一時番号）'] }, { label: '宛先ポート', cells: ['443（HTTPS）'] }] }, { kind: 'data', heading: 'データ ─ 本当に届けたい中身', items: [{ label: '中身', cells: ['TLSで暗号化された「GET / ・ Host: example.com」'] }] }]} /> },
  { id: 'outage', render: (props) => <NetworkVisual {...props} mode="nat" kicker="本の説明④：帰りはどう戻る？" heading="家の中のIPのまま、外へ出ない" lead="ルーターが送信元を書き換え、返事を元のPCへ戻す" caption="典型的な家庭のIPv4：NATの行きと帰り" note="複数のPCの区別にはポート番号も使う。" /> },
  { id: 'nat-rewrite', render: (props) => <PacketView {...props} kicker="NATの行き・中身を比べる" heading="ルーターを通ると、送信元が変わる" lead="宛先はそのまま。送信元のIPとポートだけ書き換える" caption="行き：ルーターの前後で同じパケットを比べる" note="ルーターは『61001番 ⇔ 192.168.1.10:50123』を表に記録する。" columns={[{ label: 'ルーターに入る前（家の中）' }, { label: 'ルーターを出た後（家の外）' }]} rows={[{ kind: 'ip', heading: 'IPヘッダー', items: [{ label: '送信元IP', cells: ['192.168.1.10', '198.51.100.20'], changed: true }, { label: '宛先IP', cells: ['203.0.113.10', '203.0.113.10'] }] }, { kind: 'tcp', heading: 'TCPヘッダー', items: [{ label: '送信元ポート', cells: ['50123', '61001'], changed: true }, { label: '宛先ポート', cells: ['443', '443'] }] }, { kind: 'data', heading: 'データ', items: [{ label: '中身', cells: ['暗号化されたリクエスト', '同じ（書き換えない）'] }] }]} /> },
  { id: 'nat-return', render: (props) => <PacketView {...props} kicker="NATの帰り・中身を比べる" heading="返事は表を見て、元のPCへ戻す" lead="宛先の 198.51.100.20:61001 を 192.168.1.10:50123 に戻す" caption="帰り：ルーターの前後で同じパケットを比べる" note="Webサイトから見えるのは、ルーターの 198.51.100.20 だけ。" columns={[{ label: 'Webサイトからの返事（家の外）' }, { label: 'ルーターが戻した後（家の中）' }]} rows={[{ kind: 'ip', heading: 'IPヘッダー', items: [{ label: '送信元IP', cells: ['203.0.113.10', '203.0.113.10'] }, { label: '宛先IP', cells: ['198.51.100.20', '192.168.1.10'], changed: true }] }, { kind: 'tcp', heading: 'TCPヘッダー', items: [{ label: '送信元ポート', cells: ['443', '443'] }, { label: '宛先ポート', cells: ['61001', '50123'], changed: true }] }, { kind: 'data', heading: 'データ', items: [{ label: '中身', cells: ['Webページ（暗号化）', '同じ（書き換えない）'] }] }]} /> },
  { id: 'checklist', render: (props) => <NetworkVisual {...props} mode="outage" kicker="本の説明⑤：開けなかったら？" heading="どの段階で止まったかを調べる" lead="Wi-Fi → IP設定 → DNS → 接続先 → ページの中身" caption="Wi-Fi表示だけで原因を決めつけない" note="図は回線断の例。ほかにも原因はある。" /> },
  { id: 'recap', render: ({ frame }) => <Slide tone="ink" logo><SlideHeading frame={frame} kicker="今日の答え" heading={'PC一台の通信も、\n段階を踏んで往復する'} lead="Wi-Fiで家へ → DNSで宛先IP → ルーターから外へ → 返事を受け取る" /><Callout frame={frame} label="次の疑問" icon="🔍"><p>住所のような「IP」があるのに、なぜゲートウェイが必要なのか？</p></Callout></Slide> },
  { id: 'sources', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="出典と次の話" heading="次は『IPアドレス』を解体する" lead="どこまで届ける住所なのか、実際の道筋で見る" /><Callout frame={frame} label="今回の構成の出発点" icon="📖"><p>胡田昌彦『Windowsインフラ管理者入門』（カットシステム、2014年）第3章「TCP/IPとプロトコル」・第5章「インターネット接続トラブルシューティング」。本文・図の転載ではなく、著者の問いから順に考える解説を動画向けに再構成。</p></Callout><p><a href="https://www.rfc-editor.org/rfc/rfc1918" target="_blank" rel="noreferrer">RFC 1918 · プライベートIPv4 ↗</a> <a href="https://www.rfc-editor.org/rfc/rfc5737" target="_blank" rel="noreferrer">RFC 5737 · 文書用IPv4 ↗</a> <a href="https://www.rfc-editor.org/rfc/rfc7042#section-2.1.2" target="_blank" rel="noreferrer">RFC 7042 · 文書用MAC ↗</a></p></Slide> }
]
