import type { SlideModule } from '../../../src/types'
import { Callout, DiagramFrame, FlowDiagram, Slide, SlideHeading, TitleSlide, Timeline } from '../../../src/slide-kit'
import { NetworkVisual } from '../../network-series/NetworkVisual'

export const slides: SlideModule['slides'] = [
  { id: 'opening', render: ({ frame }) => <TitleSlide frame={frame} kicker="ネットワーク超基礎 · 第1話" heading={'このPCは、どうやって\nインターネットにつながる？'} lead="Wi-Fiのマークの先を、目で追ってみよう" points={[{ step: '01', heading: '家の中', body: 'PCからWi-Fiルーターへ' }, { step: '02', heading: '家の外', body: '回線からWebサイトへ' }]} /> },
  { id: 'two-connections', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="最初の疑問" heading={'Wi-Fiにつながった ＝\nインターネットにつながった？'} lead="答えは「必ずしも、そうではない」" /><DiagramFrame frame={frame} caption="2種類のつながり" note="Wi-Fiは自宅のネットワークへの接続。外の回線は別の区間。"><FlowDiagram frame={frame} items={[{ heading: 'PC', body: '手元の端末' }, { heading: 'Wi-Fi', body: '家の中へ接続', accent: true }, { heading: '回線', body: '家の外へ接続' }, { heading: 'Web', body: 'アクセス先' }]} /></DiagramFrame><Callout frame={frame} label="よくある状態" icon="📶"><p>Wi-Fiは接続済みでも、家の外への回線が切れていればWebページは開けない。</p></Callout></Slide> },
  { id: 'route', render: (props) => <NetworkVisual {...props} mode="route" kicker="動く図①" heading="自宅のPCからWebサイトまで" lead="まず行き先へ。次に返事が戻る。" caption="家庭用IPv4ネットワークの模式図" note="点の動きは説明用。実際の経路は回線・環境によって異なる。" /> },
  { id: 'return', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="往復を一度整理" heading="送るだけでは、ページは表示されない" lead="ブラウザーの要求に、Webサイトが応答する" /><Timeline frame={frame} steps={[{ label: '①', heading: '入力', body: 'ブラウザーにURLを入力' }, { label: '②', heading: '行き', body: 'Webサイトへ要求を送る' }, { label: '③', heading: '帰り', body: '応答を受けて画面を描く', accent: true }]} /><Callout frame={frame} label="これから解く部分" icon="🔎"><p>名前から宛先を探すDNS、暗号化するHTTPSは後の回で説明する。</p></Callout></Slide> },
  { id: 'outage', render: (props) => <NetworkVisual {...props} mode="outage" kicker="動く図②" heading="Wi-Fi表示が出ていても開けない" lead="途中の線が切れたら、どこまで届く？" caption="切れる区間によって、疑う場所が変わる" note="外の回線だけでなく、DNSや接続先が原因のこともある。この図だけで原因を確定しない。" /> },
  { id: 'checklist', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="実生活で試す" heading="まず、どこまで動くか確認しよう" lead="設定を変える前に、3つの場所を見る" /><Timeline frame={frame} orientation="vertical" steps={[{ label: '1', heading: '手元', body: '端末がWi-Fiにつながっているか' }, { label: '2', heading: '家の出口', body: 'ルーターに回線の異常表示はないか' }, { label: '3', heading: '接続先', body: 'ほかのWebサイトも開けないか', accent: true }]} /><Callout frame={frame} label="無理に直さない" icon="🛡️"><p>組織のPCや自分が管理しない機器は、設定変更せず管理者に相談する。</p></Callout></Slide> },
  { id: 'recap', render: ({ frame }) => <Slide tone="ink" logo><SlideHeading frame={frame} kicker="今日の3行" heading="Wi-Fiは、インターネットの入口" lead="家の中と、家の外は別々につながっている" /><DiagramFrame frame={frame} caption="覚えるのは、この順番だけ" note="第2話：その経路で使う『IPアドレス』とは？"><FlowDiagram frame={frame} items={[{ heading: 'PC', body: 'あなたの端末' }, { heading: 'ルーター', body: '家の出口' }, { heading: '回線', body: '外への道' }, { heading: 'Web', body: '行き先' }]} /></DiagramFrame></Slide> },
  { id: 'sources', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="参考・次の話" heading="次は、行き先の『住所』を知る" lead="第2話：IPアドレスって何？" /><Callout frame={frame} label="もっと確かめたい人へ" icon="📖"><p>Internet Society「How Does the Internet Work?」、IETF RFC 1122「Requirements for Internet Hosts」。家庭構成は接続方式により異なる。</p></Callout><p><a href="https://www.internetsociety.org/internet/how-it-works/" target="_blank" rel="noreferrer">Internet Society: How the Internet Works ↗</a></p><p><a href="https://www.rfc-editor.org/rfc/rfc1122" target="_blank" rel="noreferrer">RFC 1122 ↗</a></p></Slide> }
]
