import type { SlideModule } from '../../../src/types'
import { Callout, ComparisonTable, DiagramFrame, FlowDiagram, Slide, SlideHeading, TitleSlide, VideoSlide } from '../../../src/slide-kit'
import { NetworkVisual } from '../../network-series/NetworkVisual'

export const slides: SlideModule['slides'] = [
  { id: 'opening', render: ({ frame }) => <TitleSlide frame={frame} kicker="ネットワーク超基礎 · 第3話" heading={'IPが分かったのに、\nなぜMACも必要？'} lead="『最終目的地』と『次に渡す相手』の違い" points={[{ step: '01', heading: 'IP', body: 'どこに届けたい？' }, { step: '02', heading: 'MAC', body: 'このリンクで誰に渡す？' }]} /> },
  { id: 'two-labels', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="2種類の宛先" heading="最終目的地と、次の受け渡し先" lead="Webサイトに行くときも、まずは家のルーターへ" /><ComparisonTable frame={frame} columns={[{ label: 'IPアドレス' }, { label: 'MACアドレス', accent: true }]} rows={[{ label: 'この例の相手', cells: ['WebサイトのIP', '家庭のルーターのMAC'] }, { label: '役割', cells: ['最終的に届けたい宛先', 'このリンクで渡す相手'] }, { label: '届く範囲', cells: ['ネットワークをまたぐ', '今のリンクで使う'] }]} /><Callout frame={frame} label="郵便のたとえはここまで" icon="📦"><p>IPとMACは同じ『住所』の言い換えではない。通信の違う場面で使う。</p></Callout></Slide> },
  { id: 'next-hop', render: (props) => <NetworkVisual {...props} mode="next-hop" kicker="動く図①" heading="WebサイトのMACは知らなくていい" lead="外への通信なら、家の出口＝ルーターへ渡す" caption="最終宛先IPと、次ホップのMAC" note="典型的なIPv4の例。家庭用NATでIP等が変換される場合は別の処理が加わる。" /> },
  { id: 'arp', render: (props) => <NetworkVisual {...props} mode="arp" kicker="動く図②" heading="ルーターのMACをどう知る？" lead="IPv4なら、同じリンクでARPが問い合わせる" caption="192.168.1.1 は誰？ → MACの情報を返す" note="以前調べた結果が残っていれば、毎回問い合わせない。IPv6ではNeighbor Discoveryを使う。" /> },
  { id: 'changing-links', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="境界を越えると" heading="次のリンクでは、次の宛先MACへ" lead="一つのMACアドレスが地球の裏までついていくわけではない" /><DiagramFrame frame={frame} caption="各区間のフレームを作り直す" note="IP宛先は原則維持。ただしNAT等の例外がある。"><FlowDiagram frame={frame} items={[{ heading: 'PC → ルーター', body: '自宅リンクのMAC' }, { heading: 'ルーター', body: 'フレームを作り直す', accent: true }, { heading: '次のリンク', body: 'その区間の宛先MAC' }]} /></DiagramFrame><Callout frame={frame} label="今回の図の範囲" icon="🧭"><p>家庭のEthernet／Wi-Fiを簡略化した図。すべての通信方式にMACがあるわけではない。</p></Callout></Slide> },
  { id: 'compare', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="最後に並べて確認" heading="IP＝最終宛先、MAC＝次の相手" lead="役割が違うから、両方が登場する" /><ComparisonTable frame={frame} columns={[{ label: 'IP' }, { label: 'MAC', accent: true }]} rows={[{ label: '例', cells: ['203.0.113.10', 'ルーターのMAC'] }, { label: '使いどころ', cells: ['ネットワーク間の配送', 'リンク上の受け渡し'] }, { label: '誤解', cells: ['人の身元ではない', '不変の製造番号ではない'] }]} /><Callout frame={frame} label="MACは変わることもある" icon="💡"><p>仮想NICやプライバシー保護のランダム化などがある。「絶対に変わらない」は誤り。</p></Callout></Slide> },
  { id: 'recap', render: ({ frame }) => <Slide tone="ink" logo><SlideHeading frame={frame} kicker="今日の3行" heading="外のWebサイトへ送るときも、" lead="まず家のルーターへ渡す" /><DiagramFrame frame={frame} caption="同じ1回の送信に、役割の違う情報" note="次はARPを本物の通信で見よう。"><FlowDiagram frame={frame} items={[{ heading: 'IP', body: 'Webサイトを目指す' }, { heading: 'MAC', body: 'このリンクではルーターへ', accent: true }]} /></DiagramFrame></Slide> },
  { id: 'sources', render: ({ frame }) => <VideoSlide frame={frame} kicker="本物のパケットを見よう" heading="ここから、既存のWireshark講座へ" lead="ARPとICMPの通信を画面で確かめる" videoId="DKt20AyCinI" caption="無料動画 · ARPはRFC 826、IPv6のNeighbor DiscoveryはRFC 4861を参照" /> }
]
