import type { SlideModule } from '../../../src/types'
import { Callout, CodeSlide, ComparisonTable, Slide, SlideHeading, TitleSlide, VideoSlide } from '../../../src/slide-kit'
import { NetworkVisual } from '../../network-series/NetworkVisual'
import { PacketView } from '../../network-series/PacketView'

export const slides: SlideModule['slides'] = [
  { id: 'opening', render: ({ frame }) => <TitleSlide frame={frame} kicker="ネットワーク超基礎 · 第3話" heading={'WebサイトのIPは分かった。\nでは、最初の一歩は？'} lead="本の問いを追って、PCとルーターの会話を再現しよう" points={[{ step: '01', heading: 'フレーム', body: '近くの相手へ渡す' }, { step: '02', heading: 'ARP', body: 'そのMACを調べる' }, { step: '03', heading: 'スイッチ', body: '行き先を覚える' }]} /> },
  { id: 'two-labels', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="まず封筒を二重に見る" heading="外の宛先IP／家の中の宛先MAC" lead="同じ送信でも、見る相手が違う" /><ComparisonTable frame={frame} columns={[{ label: '内側：IPパケット' }, { label: '外側：LANのフレーム', accent: true }]} rows={[{ label: 'この例の宛先', cells: ['Webサイト 203.0.113.10', '家のルーターのMAC'] }, { label: 'どこまで？', cells: ['ネットワークを越える', 'このリンクの受け渡し'] }]} /><Callout frame={frame} label="二つの住所ではなく二つの役割" icon="📦"><p>PCはWebサイトのMACを知らなくても、まずルーターへフレームを送れる。</p></Callout></Slide> },
  { id: 'next-hop', render: (props) => <NetworkVisual {...props} mode="next-hop" kicker="本の問い①：誰に渡す？" heading="Webサイト宛てを、ルーターに手渡す" lead="宛先IP＝Webサイト ／ この区間の宛先MAC＝ルーター" caption="IPパケットを、LAN上のフレームで運ぶ" note="ひとつの送信に、二種類の宛先。" /> },
  { id: 'hop-rewrite', render: (props) => <PacketView {...props} kicker="本の問い①の続き：区間が変わると？" heading="MACは区間ごとに付け替え" lead="宛先IPは最後まで同じ。宛先MACは次の区間の相手へ" caption="同じパケットを、隣り合う2つの区間で比べる" note="送信元IPが変わるのは家庭用ルーターのNATのため。" columns={[{ label: '区間①：PC → ルーター' }, { label: '区間②：ルーター → 回線事業者' }]} rows={[{ kind: 'eth', heading: 'Ethernetヘッダー ─ 区間ごとに作り直す', items: [{ label: '宛先MAC', cells: ['00-00-5E-00-53-01（ルーター）', '00-00-5E-00-53-FE（事業者）'], changed: true }, { label: '送信元MAC', cells: ['00-00-5E-00-53-10（PC）', '00-00-5E-00-53-02（ルーター外側）'], changed: true }] }, { kind: 'ip', heading: 'IPヘッダー ─ 最終目的地まで運ぶ', items: [{ label: '送信元IP', cells: ['192.168.1.10', '198.51.100.20（NAT後）'] }, { label: '宛先IP', cells: ['203.0.113.10', '203.0.113.10'] }, { label: 'TTL', cells: ['64', '63（ルーターで1減る）'] }] }, { kind: 'data', heading: 'データ', items: [{ label: '中身', cells: ['暗号化されたリクエスト', '同じ'] }] }]} /> },
  { id: 'arp', render: (props) => <NetworkVisual {...props} mode="broadcast" kicker="本の問い②：MACが分からない" heading="『192.168.1.1 は誰？』を全員へ" lead="IPv4のARP要求は、同じリンクでブロードキャスト" caption="宛先MACが不明なため、まず同じリンクの全員に尋ねる" note="一度覚えたMACは、毎回聞き直さない。" /> },
  { id: 'changing-links', render: (props) => <NetworkVisual {...props} mode="arp" kicker="本の問い③：誰が返す？" heading="該当するIPの機器だけが返答" lead="ルーターのMACを知ったら、PCは宛先欄に書ける" caption="要求は全員へ／返信は通常、問い合わせ元へ" note="返事は通常、質問したPCに直接届く。" /> },
  { id: 'arp-packet', render: (props) => <PacketView {...props} kicker="本の問い②③：ARPの中身" heading="ARPのパケットを開けてみる" lead="要求は全員宛て、応答はPC宛て。IPヘッダーは入っていない" caption="ARP要求とARP応答（Ethernetの中に直接入る）" note="探すMACが空欄の要求に、持ち主が自分のMACを書いて返す。" columns={[{ label: 'ARP要求：PC → 全員' }, { label: 'ARP応答：ルーター → PC' }]} rows={[{ kind: 'eth', heading: 'Ethernetヘッダー', items: [{ label: '宛先MAC', cells: ['FF-FF-FF-FF-FF-FF（全員）', '00-00-5E-00-53-10（PC）'], changed: true }, { label: '送信元MAC', cells: ['00-00-5E-00-53-10（PC）', '00-00-5E-00-53-01（ルーター）'] }, { label: '中身の種類', cells: ['0x0806 = ARP', '0x0806 = ARP'] }] }, { kind: 'arp', heading: 'ARPメッセージ', items: [{ label: '操作', cells: ['1 = 要求（教えて）', '2 = 応答（私です）'] }, { label: '送信者MAC', cells: ['00-00-5E-00-53-10（PC）', '00-00-5E-00-53-01（ルーター）'], changed: true }, { label: '送信者IP', cells: ['192.168.1.10', '192.168.1.1'] }, { label: '探すMAC', cells: ['00-00-00-00-00-00（不明）', '00-00-5E-00-53-10（PC）'] }, { label: '探すIP', cells: ['192.168.1.1', '192.168.1.10'] }] }]} /> },
  { id: 'compare', render: (props) => <NetworkVisual {...props} mode="switch" kicker="本の問い④：線をつなぐ箱は？" heading="スイッチは送信元MACから学ぶ" lead="宛先MACのあるポートだけへ、次のフレームを渡す" caption="MAC→ポートの表と、IP→MACのARP表は別物" note="ARP表と、スイッチのMAC表は別物。" /> },
  { id: 'recap', render: ({ frame }) => <CodeSlide frame={frame} kicker="実機で確かめる" heading="自分のPCが覚えた相手を見る" lead="Windowsで、利用中のネットワークを確認してから" caption="PowerShell／コマンドプロンプト" lines={[{ kind: 'prompt', body: 'arp -a' }, { kind: 'output', body: '192.168.1.1    00-00-5e-00-53-01' }]}><Callout frame={frame} label="これがIP→MACの表" icon="🔎"><p>値は架空の例。先に通信していなければ表示されない場合もある。実画面を公開するときは実アドレスを隠す。</p></Callout></CodeSlide> },
  { id: 'sources', render: ({ frame }) => <VideoSlide frame={frame} kicker="本の第3章 → 実物へ" heading="ARP・ICMPをWiresharkで追う" lead="原稿の問いを、本物のパケットで検証する" videoId="DKt20AyCinI" caption="無料動画 · 原稿：『Windowsインフラ管理者入門』第3章／仕様：RFC 826" /> }
]
