import type { SlideModule } from '../../../src/types'
import { Callout, CodeSlide, ComparisonTable, Slide, SlideHeading, TitleSlide } from '../../../src/slide-kit'
import { NetworkVisual } from '../../network-series/NetworkVisual'

export const slides: SlideModule['slides'] = [
  { id: 'opening', render: ({ frame }) => <TitleSlide frame={frame} kicker="ネットワーク超基礎 · 第2話" heading={'「住所」だけでは、\nIPは分からない'} lead="PCの視点になって、宛先を一歩ずつ選ぼう" points={[{ step: '01', heading: '同じ家', body: '直接届けられる？' }, { step: '02', heading: '家の外', body: '誰に渡せばいい？' }]} /> },
  { id: 'addresses', render: (props) => <NetworkVisual {...props} mode="ip" kicker="問題①：家の中の番号" heading="PCとルーターは、別のIP" lead="PCは192.168.1.10／家の出口は192.168.1.1" caption="数字は説明用。実際の番号は家によって違う" note="同じ家の中で使う、別々の番号。" /> },
  { id: 'two-scopes', render: (props) => <NetworkVisual {...props} mode="broadcast" kicker="本の問い：MACだけで十分？" heading="全世界に『あなたは誰？』とは聞けない" lead="一斉問い合わせを狭い範囲に閉じる必要がある" caption="ブロードキャストは同じリンクへ。インターネット全体には流さない" note="同じリンクの全員へ届く。外へは届かない。" /> },
  { id: 'destination', render: (props) => <NetworkVisual {...props} mode="gateway" kicker="問題②：外の番号だったら" heading="目的地はWebサイトのIP" lead="でもPCが最初に渡すのは、自宅のルーター" caption="最終宛先IPと次に渡す機器を区別する" note="外の宛先はまずルーターへ渡す。" /> },
  { id: 'can-change', render: (props) => <NetworkVisual {...props} mode="address-change" kicker="問題③：PCを別の家につないだら" heading="同じPCでもIPは変わり得る" lead="ネットワークでの居場所を表す。製造番号ではない" caption="192.168.1.10 → 192.168.1.24 は例" note="必ず変わるわけではない。" /> },
  { id: 'find-ip', render: ({ frame }) => <CodeSlide frame={frame} kicker="自分のPCで検証" heading="今の番号と家の出口を見る" lead="WindowsのPowerShell／コマンドプロンプトで実行" caption="出力は架空の例" lines={[{ kind: 'prompt', body: 'ipconfig' }, { kind: 'output', body: 'IPv4 アドレス . . . : 192.168.1.10' }, { kind: 'output', body: 'デフォルト ゲートウェイ : 192.168.1.1' }]}><Callout frame={frame} label="見るべき場所" icon="🔎"><p>利用中のWi-Fiアダプターを探そう。番号が見えても、それだけで外まで通るとは限らない。</p></Callout></CodeSlide> },
  { id: 'recap', render: ({ frame }) => <Slide tone="ink" logo><SlideHeading frame={frame} kicker="今日の答え" heading="IPは『どのネットワークの宛先か』" lead="同じネットワークなら直接。外ならゲートウェイへ。" /><ComparisonTable frame={frame} columns={[{ label: '家の中' }, { label: '家の外', accent: true }]} rows={[{ label: '最初の一歩', cells: ['相手へ直接', 'まずルーターへ'] }, { label: '共通点', cells: ['宛先IPで判断', '宛先IPで判断'] }]} /></Slide> },
  { id: 'sources', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="出典と次の話" heading="その一歩、どうやって手渡す？" lead="第3話：IPとMACアドレスの役割を分ける" /><Callout frame={frame} label="着想した原稿" icon="📖"><p>胡田昌彦『Windowsインフラ管理者入門』（カットシステム、2014年）第3章「MACアドレスだけではなぜいけないのか」「IPアドレス」。説明は動画向けに再構成。</p></Callout><p><a href="https://www.rfc-editor.org/rfc/rfc1918" target="_blank" rel="noreferrer">RFC 1918 ↗</a> <a href="https://www.rfc-editor.org/rfc/rfc5737" target="_blank" rel="noreferrer">RFC 5737（203.0.113.0/24 は文書用）↗</a></p></Slide> }
]
