import type { SlideModule } from '../../../src/types'
import { Callout, CodeSlide, ComparisonTable, DiagramFrame, FlowDiagram, Slide, SlideHeading, TitleSlide } from '../../../src/slide-kit'
import { NetworkVisual } from '../../network-series/NetworkVisual'

export const slides: SlideModule['slides'] = [
  { id: 'opening', render: ({ frame }) => <TitleSlide frame={frame} kicker="ネットワーク超基礎 · 第2話" heading={'IPアドレスって、\nいったい何？'} lead="家にPCとスマホがある。住所は同じ？" points={[{ step: '01', heading: '家の中', body: '端末ごとに宛先を分ける' }, { step: '02', heading: '家の外', body: 'ネットワークの境界を見る' }]} /> },
  { id: 'addresses', render: (props) => <NetworkVisual {...props} mode="ip" kicker="動く図①" heading="家の中でも、宛先を区別する" lead="PCとルーターには、それぞれ別のIP" caption="IPv4アドレスの例" note="192.168.1.10 / 192.168.1.1 は説明用。実際の値は環境で異なる。" /> },
  { id: 'two-scopes', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="家の内側・外側" heading="同じ『IP』でも、使う範囲が違う" lead="家の中の番号を、そのまま世界中で使うわけではない" /><ComparisonTable frame={frame} columns={[{ label: '自宅の中' }, { label: 'インターネット側', accent: true }]} rows={[{ label: '例', cells: ['192.168.1.10', '接続先: 203.0.113.10'] }, { label: '役割', cells: ['家庭内のPCを区別', '外の接続先を示す'] }, { label: '注意', cells: ['プライベートIPv4の例', '203.0.113.0/24は資料用'] }]} /><Callout frame={frame} label="家庭の外側は一通りではない" icon="🧭"><p>NAT、事業者側のNAT、IPv6などにより、実際の構成は異なる。</p></Callout></Slide> },
  { id: 'destination', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="IPの仕事" heading="『どこへ届ける？』を示す手掛かり" lead="宛先IPを見て、次に渡す先を決める" /><DiagramFrame frame={frame} caption="経路のイメージ" note="DNSがWebサイトの名前からIPを調べる仕組みは後の回で説明。"><FlowDiagram frame={frame} items={[{ heading: 'PC', body: '192.168.1.10' }, { heading: 'ルーター', body: '次のネットワークへ' }, { heading: '接続先', body: '203.0.113.10', accent: true }]} /></DiagramFrame><Callout frame={frame} label="誤解しないで" icon="💡"><p>IPは人の名前でも、端末の製造番号でもない。接続先を探すためのネットワーク上のアドレス。</p></Callout></Slide> },
  { id: 'can-change', render: (props) => <NetworkVisual {...props} mode="address-change" kicker="動く図②" heading="同じPCでも、IPは変わり得る" lead="別のWi-Fiにつないだり、割当てが更新されたりする" caption="同じ端末・違うアドレス" note="必ず変わるわけではない。固定設定や予約済み割当てもある。" /> },
  { id: 'find-ip', render: ({ frame }) => <CodeSlide frame={frame} kicker="手元で見る" heading="今のPCのアドレスを確認" lead="WindowsのPowerShellで、自分の端末だけを確認する" caption="PowerShell · Windows" lines={[{ kind: 'prompt', body: 'ipconfig' }, { kind: 'output', body: 'IPv4 Address . . . : 192.168.1.10' }, { kind: 'output', body: 'Default Gateway . : 192.168.1.1' }]}><Callout frame={frame} label="これは架空の例" icon="🔒"><p>画面を公開するなら実際のIP・SSID・端末名を隠す。複数のアダプターがあれば利用中のものを見る。</p></Callout></CodeSlide> },
  { id: 'recap', render: ({ frame }) => <Slide tone="ink" logo><SlideHeading frame={frame} kicker="今日の3行" heading="IPはネットワーク上の宛先" lead="家の中のIPと外のIPは、使われる範囲が違う" /><DiagramFrame frame={frame} caption="同じ図を、もう一度" note="第3話：IPが分かっても、なぜMACアドレスが必要？"><FlowDiagram frame={frame} items={[{ heading: '手元のPC', body: '家庭内のIP' }, { heading: 'ルーター', body: 'ネットワークの境界' }, { heading: 'Webサイト', body: '外の宛先IP' }]} /></DiagramFrame></Slide> },
  { id: 'sources', render: ({ frame }) => <Slide><SlideHeading frame={frame} kicker="参考・次の話" heading="次は、LAN内の『次の相手』へ" lead="第3話：MACアドレスって何？" /><Callout frame={frame} label="資料用の番号を使用" icon="📖"><p>192.168.1.0/24 はプライベートIPv4範囲の一例。203.0.113.0/24 は文書用で、公開サーバーの実アドレスではない。</p></Callout><p><a href="https://www.rfc-editor.org/rfc/rfc1918" target="_blank" rel="noreferrer">RFC 1918 · Private Address Space ↗</a></p><p><a href="https://www.rfc-editor.org/rfc/rfc5737" target="_blank" rel="noreferrer">RFC 5737 · Documentation Addresses ↗</a></p></Slide> }
]
